services:
  api:
    build: .
    container_name: simple_discord_api
    ports:
      - "8000:8000"
    environment:
      - API_PORT=8000
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      dynamodb:
        condition: service_started
      table-init:
        condition: service_completed_successfully

  dynamodb:
    image: amazon/dynamodb-local
    container_name: simple_discord_db
    ports:
      - "8010:8000"

  table-init:
    build: .
    container_name: simple_discord_init
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      - dynamodb
    command: python infra/local/init_db.py --table-file config/tables.json