services:
  api:
    build: backend
    ports:
      - "8000:8000"
    environment:
      - API_PORT=8000
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      dynamodb:
        condition: service_started
      init:
        condition: service_completed_successfully
    volumes:
      - ./backend/:/app/ # hot reload for backend
    command: uvicorn src.harmony.app.main:app --host 0.0.0 --port 8000 --reload

  frontend:
    build: 
      context: frontend
      args:
        - NODE_ENV=production
        - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
        - NEXT_PUBLIC_INTERNAL_API_URL=http://api:8000/api/v1
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
      - NEXT_PUBLIC_INTERNAL_API_URL=http://api:8000/api/v1
    depends_on:
      api:
        condition: service_started

  dynamodb:
    image: amazon/dynamodb-local
    container_name: db

  init:
    build: backend
    container_name: init
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      - dynamodb
    volumes:
      - ./infra/:/app/infra/:ro
    command: python infra/local/init_db.py --table-file infra/config/tables.json
