services:
  api:
    build: backend
    environment:
      - API_PORT=8000
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      dynamodb:
        condition: service_started
      init:
        condition: service_completed_successfully

  dynamodb:
    image: amazon/dynamodb-local
    container_name: simple_discord_db

  init:
    build: backend
    container_name: simple_discord_init
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      - dynamodb
    volumes:
      - ./infra/:/app/infra/:ro
    command: python infra/local/init_db.py --table-file infra/config/tables.json