name: simple-discord
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - expat=2.7.3=h50f4ffc_4
  - libcxx=21.1.8=hb4ce287_0
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.19=ha0b305a_0
  - packaging=25.0=py312hca03da5_1
  - pip=25.3=pyhc872135_0
  - python=3.12.12=h2bfc596_1
  - readline=8.3=h0b18652_0
  - setuptools=80.10.1=py312hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025c=he532380_0
  - wheel=0.46.3=py312hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - aioboto3==15.5.0
      - aiobotocore==2.25.1
      - aiofiles==25.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aioitertools==0.13.0
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.1
      - attrs==25.4.0
      - boto3==1.40.61
      - botocore==1.40.61
      - build==1.4.0
      - certifi==2026.1.4
      - click==8.3.1
      - fastapi==0.128.0
      - frozenlist==1.8.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - iniconfig==2.3.0
      - jmespath==1.1.0
      - multidict==6.7.1
      - pip-tools==7.5.2
      - pluggy==1.6.0
      - propcache==0.4.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pygments==2.19.2
      - pyproject-hooks==1.2.0
      - pytest==9.0.2
      - pytest-asyncio==1.3.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-ulid==3.1.0
      - s3transfer==0.14.0
      - simple-discord==0.1.0
      - six==1.17.0
      - starlette==0.50.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.6.3
      - uvicorn==0.40.0
      - wrapt==1.17.3
      - yarl==1.22.0
prefix: /opt/homebrew/anaconda3/envs/simple-discord
