services:
  loadbalancer:
    image: nginx:alpine
    container_name: lb
    ports:
      - "8000:80"
    volumes:
      - ./infra/local/nginx.conf:/etc/nginx/nginx.conf:ro 
    depends_on:
      - api

  api:
    deploy:
      replicas: 4